version: '3.8'

services:
  wrls-db:
    image: postgres
    container_name: wrls-db
    volumes:
      - wrls_db_volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: water_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permits

  redis:
    image: redis
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

volumes:
  wrls_db_volume:
  cache:
    driver: local